# Generated by Django 4.1.4 on 2023-01-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_group_name_alter_group_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.CharField(max_length=20, verbose_name='Курс/Направление'),
        ),
        migrations.AlterField(
            model_name='group',
            name='maxAge',
            field=models.PositiveIntegerField(verbose_name='Максимальный возраст'),
        ),
        migrations.AlterField(
            model_name='group',
            name='minAge',
            field=models.PositiveIntegerField(verbose_name='Минимальный возраст'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
