# Generated by Django 4.1.4 on 2023-01-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_group_capacity_alter_group_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
