# Generated by Django 4.1.4 on 2023-01-25 16:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='dateOfBirth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='phoneNumber',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона'),
        ),
    ]
