# Generated by Django 4.1.4 on 2023-01-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_groupmember_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество записанных'),
            preserve_default=False,
        ),
    ]
